swagger: "2.0"
info:
  description: |
    The Arsa API is orgnaized around the REST methodology. It uses resource-oriented URLs and common HTTP response codes to indicate API errors.

    All requests must be authenticated via OAuth2. All API responses return JSON.
  version: "0.0.1"
  title: "Arsa"
  termsOfService: "https://arsa.io/terms/"
  contact:
    email: "apiteam@arsa.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "api.arsa.io"
basePath: "/v1"
tags:
- name: "pools"
  description: |
    A data pool is a collection of data files with the same taxonomy. It securely stores your data in a compressed and queryable format to allow workflows to access the data inside. When you create a data pool, you must define a taxonomy. Any data file sent to a data pool must match that taxonomy. Every file sent to a data pool gets appended with a "file_id" and "timestamp" attribute.

    The data inside of data pools is immutable and can be accessed via SQL at any time through a unique data pool endpoint. Arsa optimizes the data pools to allow for special SQL functions such as "ranking" to be performed over a data pool so you can gather the most recent iterations of your data. Arsa charges for the amount of data scanned for each query.

    Data files can be uploaded to Arsa through provider integrations. When a data pool is created, provider integrations can be added to enable access to upload data files. Data files can be uploaded via HTTPS, S3, or SFTP providers. A data pool can also be shared as a provider to enable access from third party users.
- name: "files"
  description: "Data files that are uploaded to a data pool."
- name: "transforms"
  description: |
    Transformations are processes that can be executed against a incoming dataset and return a new transformed dataset. A transformation process can be built as either a Docker image or a Apache Spark script. In each case, easy integration points are provided to read and write data in and out of your transformation. This allows you to focus on the application logic and not worry about data integration.

    A transformation must adhere to a defined input and output taxonomy. Arsa validates that the data getting sent in and the data returned match the taxonomy defined in the transformation.

    When creating a transformation, a user can specify how many resources the transformation can consume. This will effect the time it takes to complete the transformation. Arsa charges by the hour for each execution of a transformation based upon the resources set. A user can set the number of vCPUs and memory a transformation has access to.
- name: "workflows"
  description: |
    A workflow in Arsa is a DAG (Direct Acyclic Graph) of transformations. It is defined as a state machine that tells Arsa how to process the DAG. A workflow can be defined via a Arsa Workflow YAML and uploaded to the platform via the Arsa CLI.

    A workflow must be tied to a source data pool. This tells the workflow where to begin to read the data.  It can query from multiple data pools throughout the workflow, but must read from at least one parent data pool. A workflow can accept input parameters at runtime and can be schedule to repeat at time intervals or when a new data file is delivered on the source data pool.
- name: "interfaces"
  description: |
    An interface provides read or write access to a data pool for an individual or system. Data pool owners can specify who or what they want to share access with by creating an interface associated to a data pool.

    Each interface must conform to a supported access operation. The currently supported interfaces are: S3, HTTP, SFTP, or JDBC. Once a interface is created, Arsa will supply the credentials needed to access the data pool.
- name: "jobs"
  description: "Workflow executions."
schemes:
- "https"
paths:
  /pools:
    get:
      tags:
        - "pools"
      summary: "List the available data pools"
      description: ""
      operationId: "listPools"
      security:
      - api_key:
        - "read:pools"
    post:
      tags:
        - "pools"
      summary: "Create a new data pool"
      description: ""
      operationId: "createPool"
      security:
        - api_key:
          - "write:pools"
          - "read:pools"
  /pools/{poolId}:
    get:
      tags:
        - "pools"
      summary: "Find pool by ID"
      description: "Returns a single pool"
      operationId: "getPoolById"
      security:
        - api_key:
          - "write:pools"
          - "read:pools"
    delete:
      tags:
        - "pools"
      summary: "Delete pool by ID"
      description: "Deletes a single pool"
      operationId: "deletePoolById"
      security:
        - api_key:
          - "write:pools"
          - "read:pools"
  /transforms:
    get:
      tags:
        - "transforms"
      summary: "List the available transforms"
      description: ""
      operationId: "listTransforms"
      security:
      - api_key:
        - "read:transforms"
    post:
      tags:
        - "transforms"
      summary: "Create a new transform"
      description: ""
      operationId: "createTransform"
      security:
        - api_key:
          - "write:transforms"
          - "read:transforms"

  /transforms/{transformId}:
    get:
      tags:
        - "transforms"
      summary: "Find transform by ID"
      description: "Returns a single transform"
      operationId: "getTransformById"
      security:
        - api_key:
          - "write:transforms"
          - "read:transforms"
    put:
      tags:
        - "transforms"
      summary: "Update transform by ID"
      description: "updates a single transform"
      operationId: "updateTransformById"
      security:
        - api_key:
          - "write:transforms"
          - "read:transforms"
    delete:
      tags:
        - "transforms"
      summary: "Delete transform by ID"
      description: "Deletes a single transform"
      operationId: "deleteTransformById"
      security:
        - api_key:
          - "write:transforms"
          - "read:transforms"

  /pools/{poolId}/workflows:
    get:
      tags:
        - "workflows"
      summary: "Find workflows by pool ID"
      description: "Returns a list of available workflows"
      operationId: "getWorkflowsByPoolById"
      security:
        - api_key:
          - "write:pools"
          - "read:pools"
    post:
      tags:
        - "workflows"
      summary: "Create a new workflow"
      description: ""
      operationId: "createWorkflow"
      security:
        - api_key:
          - "write:pools"
          - "read:pools"
  /pools/{poolId}/workflows/{workflowId}:
    get:
      tags:
        - "workflows"
      summary: "Find workflows by pool ID"
      description: "Returns a list of available workflows"
      operationId: "getWorkflowById"
      security:
        - api_key:
          - "write:pools"
          - "read:pools"
    put:
      tags:
        - "workflows"
      summary: "Update a workflow"
      description: ""
      operationId: "updateWorkflowById"
      security:
        - api_key:
          - "write:pools"
          - "read:pools"
    delete:
      tags:
        - "workflows"
      summary: "Delete a workflow"
      description: ""
      operationId: "deleteWorkflowById"
      security:
        - api_key:
          - "write:pools"
          - "read:pools"
  /pools/{poolId}/interfaces:
    get:
      tags:
        - "interfaces"
      summary: "Find interfaces by pool ID"
      description: "Returns a list of available interfaces"
      operationId: "listInterfacesByPoolById"
      security:
        - api_key:
          - "write:pools"
          - "read:pools"
    post:
      tags:
        - "interfaces"
      summary: "Create a new interface"
      description: ""
      operationId: "createInterface"
      security:
        - api_key:
          - "write:pools"
          - "read:pools"
  /pools/{poolId}/files:
    get:
      tags:
        - "files"
      summary: "Find files by pool ID"
      description: "Returns a list of available files per pool"
      operationId: "getFilesByPoolById"
      security:
        - api_key:
          - "write:pools"
          - "read:pools"
  /jobs:
    get:
      tags:
        - "jobs"
      summary: "List the available jobs"
      description: ""
      operationId: "listJobs"
      security:
      - api_key:
        - "read:jobs"
  /jobs/{jobId}:
    get:
      tags:
        - "jobs"
      summary: "Find job by ID"
      description: "Returns a single job"
      operationId: "getJobById"
      security:
        - api_key:
          - "read:jobs"

securityDefinitions:
  api_key:
    type: "apiKey"
    name: "x-api-key"
    in: "header"